# Site settings
author: Matthew Palmer
title: Journey to Full Stack Website Developer
header-img: img/home-bg.png
email: matthewpalmer9@outlook.com
copyright_name: Matthew Palmer
description: > # this means to ignore newlines until "baseurl:"
  A journal documenting the struggles and success of my journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MatthewPalmer9

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
