# Site settings
author: Matthew Ryan Palmer
title: 
header-img: img/home-bg.png
email: matthewpalmer9@outlook.com
copyright_name: Matthew Ryan Palmer
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MatthewPalmer9

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
